package com.galaxyyao.springbootdroolstest1
import com.lovejobs.springboot.drools.model.Message
dialect  "mvel"

rule "Hello World"
    dialect "mvel"
    when
        m : Message(status.equals(Message.HELLO), message : message )
    then
        modify ( m ) { message = "Goodbye cruel world",status = Message.GOODBYE };
        System.out.println("Hello World rule mesg:"+message);
end

rule "Good Bye"
    dialect "java"
    when
       Message( status == Message.GOODBYE, message : message )
    then
        System.out.println("Good Bye rule mesg:"+message);
end
